CooverBoxWebApplication/Controllers/BoxesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CooverBoxWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using CooverBoxWebApplication.Models.Boxes;
using Microsoft.Extensions.Primitives;
using CooverBoxWebApplication.ViewModels;
using CooverBoxWebApplication.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace CooverBoxWebApplication.Controllers
{
    [Route("[controller]")]
    [Authorize(Roles = "master, admin, user")]
    public class BoxesController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private DBAppContext _context;

        public BoxesController(IWebHostEnvironment webHostEnvironment, DBAppContext context, ILogger<BoxesController> logger)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }
        //Id может соотвествовать имении класса (тогда создаться новая модель по умолчанию) или имени файла (модель будет загружена из файла)
        //Id уникальный для каждого файла, и является частью строки запроса
        [HttpGet("{Id}")]
        public IActionResult Index(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model != null)
            {
                //если пользователь который открыл модел не является её создателем или мастером, сбрасывается Id модели, чтобы в при переходе дальше создаласть копия
                if(model.UserName != User.Identity.Name && !User.IsInRole("master")) model.Id = $"{model.GetType().Name}";
                return View(model);
            }
            return RedirectToAction("FunError", "Home");
        }
        [HttpPost("{Id}")]
        public IActionResult Index(string Id, BaseBox model)
        {
            if (!ModelState.IsValid)
            {
                model.Id = Id;
                return View(model);
            }
            if (model == null) return RedirectToAction("FunError", "Home");
            if(model.Id == null || model.Id == $"{model.GetType().Name}")
            {
                if(Id == $"{model.GetType().Name}")
                    model.Id = $"{Guid.NewGuid()}";
                else
                    model.Id = Id;
            }
            //задает создателя
            if (string.IsNullOrEmpty(model.UserName)) model.UserName = User?.Identity?.Name;
            //если Identity не содежит имя пользователя
            if (string.IsNullOrEmpty(model.UserName)) { model.UserName = "erroruser"; }
            _context.SaveDBBox(model);

#if RELEASE
            {
                BoxDBDataTest boxDB = _context.BoxesTestSaved.FirstOrDefault(b => b.Id == model.Id);
                if (boxDB is null)
                {
                    boxDB = new BoxDBDataTest()
                    {
                        Id = model.Id,
                        FullName = model.FullName,
                        BitrixLink = model.BitrixLink,
                        TypeBox = model.TypeBoxe,
                        UserId = _context.Users.First(u => u.UserName == User.Identity.Name).Id,
                        DateCreated = DateTime.Now
                    };
                    _context.BoxesTestSaved.Add(boxDB);
                }
                else
                {
                    boxDB.FullName = model.FullName;
                    boxDB.DateCreated = DateTime.Now;
                }
                _context.SaveChanges();
            }
#endif
            Id = model.Id;
            if (model == null) return RedirectToAction("FunError", "Home");
            return RedirectToAction($"Preview", routeValues: new { Id });
        }
        //создает клона модели, просто стирает Id и вписывает нового создателя
        //НИКТО НЕ ПОЛЬЗУЕТСЯ
        [HttpGet("Clone/{Id}")]
        public IActionResult Clone(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model != null)
            {
                model.UserName = User?.Identity?.Name;
                if (string.IsNullOrEmpty(model.UserName)) { model.UserName = "erroruser"; }
                model.Id = $"{model.GetType().Name}";
                return View("~/Views/Boxes/Index.cshtml", model);
            }
            return RedirectToAction("FunError", "Home");
        }
        //выводит станицу с параметрами модели и себестоимостью
        [HttpGet("Preview/{Id}")]
        public IActionResult Preview(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");
            return View(model);
        }
        //страница Preview выводит только параметры без себестоимости
        //себестоимоть выводится через ajax запрос к методу ниже
        //если ajax-у вернулся error то пытается вызвать этот метод, который выводит всё сразу
        [HttpGet("PreviewAJAXERROR/{Id}")]
        public IActionResult PreviewAJAXERROR(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");
            return View(model);
        }
        //метод для обработки ajax запроса со страницы Preview
        [HttpGet("CostViewJquery")]
        public IActionResult CostViewJquery(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);

            if (model == null) return RedirectToAction("FunError", "Home");
            model.Create();

            return View(model);
        }
        
        //сохранить в личный список заказов
        [HttpGet("Save/{Id}")]
        public IActionResult Save(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");
            model.Id = $"{System.Guid.NewGuid()}";
            _context.SaveDBBox(model);
            BoxDBData boxDB = new BoxDBData()
            {
                Id = model.Id,
                FullName = model.FullName,
                BitrixLink = model.BitrixLink,
                TypeBox = model.TypeBoxe,
                UserId = _context.Users.First(u => u.UserName == User.Identity.Name).Id,
                DateCreated = DateTime.Now
            };
            _context.BoxesSaved.Add(boxDB);
            _context.SaveChanges();
            return RedirectToAction($"Index", "JSONBox");
        }
        //скачать чертежи, раскрой, упаковку
        [HttpGet("Download/{Id}")]
        public FileResult Download(string Id)
        {
            string Path = $"{_webHostEnvironment.WebRootPath}\\FileTemp\\{System.Guid.NewGuid()}";
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return null;
            if (Directory.CreateDirectory(Path) != null)
            {
                model.Create(Path);
                ZipFile.CreateFromDirectory(Path, $"{Path}.zip");
                Task.Run(() => DeleteCreationFiles(Path));
                System.IO.FileStream fs = new System.IO.FileStream($"{Path}.zip", System.IO.FileMode.Open);
                return File(fs, "application/octet-stream", $"{model.FullName}.zip");
            }
            return null;
            //удаляет созданую папку и архив через минутя 
            static void DeleteCreationFiles(string Path)
            {
                Thread.Sleep(TimeSpan.FromMinutes(1));
                Directory.Delete(Path, true);
                System.IO.File.Delete($"{Path}.zip");
            }
        }
        //скачать крой для дизайнеров
        [HttpGet("DownloadDisign/{Id}")]
        public FileResult DownloadDisign(string Id)
        {
            string Path = $"{_webHostEnvironment.WebRootPath}\\FileTemp\\{System.Guid.NewGuid()}.pdf";
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return null;
            string PathConst = $"{_webHostEnvironment.WebRootPath}\\BoxesDisigns\\{model.GetType().Name}.pdf";

            model.CreateDisignPDF(PathConst, Path);
            Task.Run(() => DeleteCreationFile(Path));
            System.IO.FileStream fs = new System.IO.FileStream($"{Path}", System.IO.FileMode.Open);
            return File(fs, "application/pdf", $"{model.FullName}.pdf");

            static void DeleteCreationFile(string Path)
            {
                Thread.Sleep(TimeSpan.FromMinutes(1));
                System.IO.File.Delete($"{Path}");
            }

        }


        //создать сделку, запрос для получения ссылки на битрикс
        [HttpGet("DownloadOrder/{Id}")]
        public IActionResult DownloadOrder(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");

            ViewBag.BoxId = Id;
            ViewBag.BoxName = model.FullName;
            ViewBag.BitrixLink = model.BitrixLink;
            return View("~/Views/Boxes/DownloadOrder.cshtml");
        }
        [HttpPost("DownloadOrder/{Id}")]
        public IActionResult DownloadOrder(string Id, string BitrixLink)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return null;
            if (string.IsNullOrEmpty(BitrixLink) || !Uri.IsWellFormedUriString(BitrixLink, UriKind.Absolute) || !(new[] { "bitrix24", "likepackage" }.Any(s => BitrixLink.Contains(s) is true)))
            {
                ModelState.AddModelError("", "ссылка на bitrix24 обязательна");
                ViewBag.BoxId = Id;
                ViewBag.BoxName = model.FullName;
                return View("~/Views/Boxes/DownloadOrder.cshtml");
            }
            model.BitrixLink = BitrixLink;
            model.Create();
            _context.SaveDBBox(model);

CooverBoxWebApplication/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CooverBoxWebApplication.Models;
using CooverBoxWebApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Math;
using Microsoft.EntityFrameworkCore;
using CooverBoxWebApplication.Models.WorkRecord;

namespace CooverBoxWebApplication.Controllers
{
    [Authorize(Roles = "master")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;
        RoleManager<IdentityRole> _roleManager;
        private DBAppContext _context;
        public UsersController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, DBAppContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> IndexAsync()
        {
            List<User> users = _userManager.Users.ToList();
            List<UserViewModel> usersview = new List<UserViewModel>();
            foreach(User var in users)
            {
                usersview.Add(new UserViewModel {UserName = var.UserName,Id = var.Id, Roles = (List<string>)await _userManager.GetRolesAsync(var),Departments = _context.Departments.Include(k=>k.UsersAndDepartnments).Where(d=>d.UsersAndDepartnments.Any(u=>u.UserId==var.Id)).Select(d=>d.Name).ToList()});
            }
            return View(usersview);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Roles = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { UserName = model.UserName };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, model.Role);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> ResetPassword(string id)
        {
            User qw = await _userManager.FindByIdAsync(id);
            User user = await _userManager.FindByNameAsync(qw.UserName);
            if (user == null)
            {
                return NotFound();
            }
            string code = await _userManager.GeneratePasswordResetTokenAsync(user);
            return View(new Dictionary<string, string> { { "userId", $"{user.Id}" }, { "code", code } });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var allDepartments = _context.Departments.ToList();
                var userDepartments = _context.Users.Include(k => k.UsersAndDepartnments).First(u=>u.Id==user.Id).UsersAndDepartnments.Where(ud =>ud.DepartmentId != null).Select(ud =>ud.DepartmentId.Value).ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    UserRoles = userRoles,
                    AllRoles = allRoles,
                    AllDepartments = allDepartments,
                    UserDepartments = userDepartments
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string id, List<string> roles,List<int> departnments)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);
                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                var ud = _context.Users.Include(k => k.UsersAndDepartnments).First(u =>u.Id == user.Id);
                ud.UsersAndDepartnments.RemoveAll(d => !departnments.Contains(d.Id));
                foreach(var d in departnments.Where(id => ud.UsersAndDepartnments.All(qw => qw.DepartmentId!=id)))
                {
                    ud.UsersAndDepartnments.Add(new UsersAndDepartnments() {UserId = ud.Id,DepartmentId = d }); 
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult AddRoll()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRoll(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                name = name.Trim();
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("RollsList");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }
        [HttpGet]
        public IActionResult RollsList()
        {
            return View(_roleManager.Roles.ToList());
        }
        [HttpPost]
        public async Task<IActionResult> DeleteRoll(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("RollsList");
        }
    }
}

CooverBoxWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Like Package</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootswatch/solar/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Stylesheet", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Like Package</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Переплет</a>
                            <div class="dropdown-menu  bg-primary">
                                <a class="nav-link" asp-action="Index" asp-route-Id="TopBotton" asp-controller="Boxes">Крышка Дно</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="BookWithString" asp-controller="Boxes">Книга с лентой</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="BookValve" asp-controller="Boxes">Книга с клапаном</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="Cub" asp-controller="Boxes">Кубик</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="OptimusPride" asp-controller="Boxes">Самосборная</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="Bumblebee" asp-controller="Boxes">Самосборная упр</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="Slider" asp-controller="Boxes">Слайдер</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="CircleTopBotton" asp-controller="Boxes">Тубус</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">МДФ</a>
                            <div class="dropdown-menu  bg-primary">
                                <a class="nav-link" asp-action="Index" asp-route-Id="Casket" asp-controller="Boxes">Шкатулка</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="SliderMDF" asp-controller="Boxes">Слайдер МДФ</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="BookWithStringMDF" asp-controller="Boxes">Книга с лентой МДФ</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="BookValveMDF" asp-controller="Boxes">Книга с клапаном МДФ</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="Mercedes" asp-controller="Boxes">Мерседес</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Крафт</a>
                            <div class="dropdown-menu  bg-primary">
                                <a class="nav-link" asp-action="Index" asp-route-Id="CraftTopBottonOptimus" asp-controller="Boxes">Крышка дно самосборная</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="CraftWithEars" asp-controller="Boxes">С ушами</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Гофра</a>
                            <div class="dropdown-menu  bg-primary">
                                <a class="nav-link" asp-action="Index" asp-route-Id="GofraTopBottonOptimus" asp-controller="Boxes">Крышка дно самосборная</a>
                                <a class="nav-link" asp-action="Index" asp-route-Id="GofraWithEars" asp-controller="Boxes">С ушами</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Пакеты</a>
                            <div class="dropdown-menu  bg-primary">
                                <a class="nav-link" asp-action="Index" asp-route-Id="CatHouse" asp-controller="Boxes">Пакет :-/</a>
                            </div>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated && User.IsInRole("master"))
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="JSONBox" asp-action="TextFileView">Тесты</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated && (User.IsInRole("workmanager") || User.IsInRole("worker")))
                    {
                        <li class="nav-item active">
                            <a class="nav-link"  asp-controller="Department" asp-action="Index">Департаменты</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated && User.IsInRole("master"))
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Index">Сделки</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Knife" asp-action="Index">Ножы</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                        </li>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="JSONBox" asp-action="Index">Заказы</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout" onclick="return confirm('Вы уверены?')">[@User.Identity.Name]Выйти</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <br />
    <div class="container">
        @RenderBody()
    </div>
    <br />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>