CooverBoxWebApplication/Controllers/PostPackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CooverBoxWebApplication.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using PDFCore;
using PDFCore.Graphic;
using CooverBoxWebApplication.Models.Boxes.Helpers;

namespace CooverBoxWebApplication.Controllers
{
    //использовался для тестирования алгоритма упаковки изделий в коробочки
    public class PostPackageController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        public PostPackageController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(PostPackageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            PostLiker2 postLiker = new PostLiker2(model.X,model.Y,model.H,model.Weight,model.N);
            postLiker.Work();
            return View("PostLiker", postLiker);
        }

        [HttpPost]
        public FileResult Download(PostPackageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return null;
            }
            PostLiker2 postLiker = new PostLiker2(model.X, model.Y, model.H, model.Weight, model.N);
            string Path = $"{_webHostEnvironment.WebRootPath}\\FileTemp";
            string fullName = $"{ System.Guid.NewGuid() }";
            postLiker.Work(fullName,Path);
            Task.Run(() => DeleteCreationFiles($"{Path}\\Упаковка {fullName}.pdf"));
            System.IO.FileStream fs = new System.IO.FileStream($"{Path}\\Упаковка {fullName}.pdf", System.IO.FileMode.Open);
            return File(fs, "application/octet-stream", $"Упаковка {model.X}x{model.Y}x{model.H} -{model.N}.pdf");


            static void DeleteCreationFiles(string Path)
            {
                Thread.Sleep(TimeSpan.FromMinutes(1));
                System.IO.File.Delete($"{Path}.pdf");
            }
        }

    }
}

CooverBoxWebApplication/Views/PostPackage/Index.cshtml
@model CooverBoxWebApplication.ViewModels.PostPackageViewModel
@{
    ViewData["Title"] = "Упаковка коробочек";
}

<div class="jumbotron">
    <form method="post" asp-action="Index" asp-controller="PostPackage" asp-anti-forgery="true">
        <fieldset>
            <legend>Размеры коробки</legend>
            <div class="form-group row">
                <label class="col-md-3 col-xs-12" asp-for="X"></label>
                <div class="col-md-9 col-xs-12">
                    <input class="form-control" asp-for="X" />
                </div>
                <span class="col-md-12 col-xs-12 text-warning" asp-validation-for="X" />
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-xs-12" asp-for="Y"></label>
                <div class="col-md-9 col-xs-12">
                    <input class="form-control" asp-for="Y" />
                </div>
                <span class="col-md-12 col-xs-12 text-warning" asp-validation-for="Y" />
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-xs-12" asp-for="H"></label>
                <div class="col-md-9 col-xs-12">
                    <input class="form-control" asp-for="H" />
                </div>
                <span class="col-md-12 col-xs-12 text-warning" asp-validation-for="H" />
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-xs-12" asp-for="Weight"></label>
                <div class="col-md-9 col-xs-12">
                    <input class="form-control" asp-for="Weight" />
                </div>
                <span class="col-md-12 col-xs-12 text-warning" asp-validation-for="Weight" />
            </div>
            <div class="form-group row">
                <label class="col-md-3 col-xs-12" asp-for="N"></label>
                <div class="col-md-9 col-xs-12">
                    <input class="form-control" asp-for="N" />
                </div>
                <span class="col-md-12 col-xs-12 text-warning" asp-validation-for="N" />
            </div>
            <input class="btn btn-secondary m-1" type="submit" value="Далее" />
        </fieldset>
    </form>
</div>

@section scripts{
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

CooverBoxWebApplication/Views/PostPackage/PostLiker.cshtml
@model CooverBoxWebApplication.Models.Boxes.Helpers.PostLiker2
@{
    ViewData["Title"] = $"Упаковка коробочек {Model.Box.X}x{Model.Box.Y}x{Model.Box.H}";
    void packageView(CooverBoxWebApplication.Models.Boxes.Helpers.Package package, CooverBoxWebApplication.Models.Boxes.Helpers.Package packageadd)
    {
        @if (package != null)
        {
            bool add = packageadd != null;
            <div class="lead row">
                <p class="col-xs-12 col-md-4">@($"{package.Name}  {Math.Round(package.Weight / 1000, 3)} кг  Объем {Math.Round(package.Volume, 3)} м3")</p>
                <p class="col-xs-12 col-md-8">@($"Посылок {package.Count+((add)? packageadd.Count:0)} Общий объем {Math.Round(package.Volume * package.Count + ((add) ? packageadd.Volume * packageadd.Count : 0), 3)} м3")</p>
            </div>
        }
    }
}


<div class="jumbotron">
    @if (Model != null)
    {
        <div class="jumbotron costviewtop">
            <h1 class="col-12 text-center">Экспортная отправка</h1>
            @{packageView(Model.UKRPOST_B, Model.UKRPOST_Badd);}

            @{packageView(Model.Herson_G20, Model.Herson_G20add);}
            @{packageView(Model.Herson_G30, Model.Herson_G30add);}

            @{packageView(Model.Koktebel_G20, Model.Koktebel_G20add);}
            @{packageView(Model.Koktebel_G30, Model.Koktebel_G30add);}



            <a href="https://www.ukrposhta.ua/ru/katehorii-vidpravlen" target="_blank">Укрпошта</a>
        </div>
        <form method="post" asp-action="Download" asp-controller="PostPackage" asp-anti-forgery="true">
            <input class="d-none" name="X" value=@Model.Box.X />
            <input class="d-none" name="Y" value=@Model.Box.Y />
            <input class="d-none" name="H" value=@Model.Box.H />
            <input class="d-none" name="Weight" value=@Model.Weight />
            <input class="d-none" name="N" value=@Model.N />
            <input class="btn btn-secondary m-1" type="submit" value="Скачать" />

        </form>
    }

</div>