InputValues/Components/InputValueDisplayViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CooverBoxWebApplication.Components
{
    public class InputValueDisplayViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(dynamic model, InputValues.Base.BaseInputValue inputValue = null)
        {
            if (inputValue == null)
            {
                try
                {
                    List<InputValues.Base.BaseInputValue> inputValues = (List<InputValues.Base.BaseInputValue>)model.GetType().GetProperty("InputValues").GetValue(null);
                    ViewBag._model = model;
                    return View($"~/InputValues/Base/BaseDisplay.cshtml", inputValues);
                }
                catch(Exception e)
                {
                    throw new Exception($"{model.GetType()} не содержит статическое поле List<InputValues.Base.BaseInputValue> InputValues. {e.Message}");
                }

            }
            else
            {
                if(string.IsNullOrEmpty(inputValue.Roll) is false && User?.IsInRole(inputValue.Roll) is false)
                {
                    return Content(string.Empty);
                }
                ViewBag._model = model;
                return View($"~/InputValues/InputValuesDisplay/{inputValue.GetType().Name.Replace("InputValue", "").Replace("`1", "")}.cshtml", inputValue);
            }
        }
    }
}

InputValues/Components/InputValueViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CooverBoxWebApplication.Components
{
    public class InputValueViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(dynamic model, InputValues.Base.BaseInputValue inputValue = null)
        {
            if (inputValue == null)
            {
                try
                {
                    List<InputValues.Base.BaseInputValue> inputValues = (List<InputValues.Base.BaseInputValue>)model.GetType().GetProperty("InputValues").GetValue(null);
                    ViewBag._model = model;
                    return View($"~/InputValues/Base/BaseView.cshtml", inputValues);
                }
                catch(Exception e)
                {
                    throw new Exception($"{model.GetType()} не содержит статическое поле List<InputValues.Base.BaseInputValue> InputValues. {e.Message}");
                }

            }
            else
            {
                if(string.IsNullOrEmpty(inputValue.Roll) is false && User?.IsInRole(inputValue.Roll) is false)
                {
                    return Content(string.Empty);
                }
                ViewBag._model = model;
                return View($"~/InputValues/InputValuesView/{inputValue.GetType().Name.Replace("InputValue", "").Replace("`1", "")}.cshtml", inputValue);
            }
        }
    }
}

InputValues/Controllers/BoxesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CooverBoxWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using CooverBoxWebApplication.Models.Boxes;
using Microsoft.Extensions.Primitives;
using CooverBoxWebApplication.ViewModels;
using CooverBoxWebApplication.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace CooverBoxWebApplication.Controllers
{
    [Route("[controller]")]
    [Authorize(Roles = "master, admin, user")]
    public class BoxesController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private DBAppContext _context;

        public BoxesController(IWebHostEnvironment webHostEnvironment, DBAppContext context, ILogger<BoxesController> logger)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }
        //Id может соотвествовать имении класса (тогда создаться новая модель по умолчанию) или имени файла (модель будет загружена из файла)
        //Id уникальный для каждого файла, и является частью строки запроса
        [HttpGet("{Id}")]
        public IActionResult Index(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model != null)
            {
                //если пользователь который открыл модел не является её создателем или мастером, сбрасывается Id модели, чтобы в при переходе дальше создаласть копия
                if(model.UserName != User.Identity.Name && !User.IsInRole("master")) model.Id = $"{model.GetType().Name}";
                return View(model);
            }
            return RedirectToAction("FunError", "Home");
        }
        [HttpPost("{Id}")]
        public IActionResult Index(string Id, BaseBox model)
        {
            if (!ModelState.IsValid)
            {
                model.Id = Id;
                return View(model);
            }
            if (model == null) return RedirectToAction("FunError", "Home");
            if(model.Id == null || model.Id == $"{model.GetType().Name}")
            {
                if(Id == $"{model.GetType().Name}")
                    model.Id = $"{Guid.NewGuid()}";
                else
                    model.Id = Id;
            }
            //задает создателя
            if (string.IsNullOrEmpty(model.UserName)) model.UserName = User?.Identity?.Name;
            //если Identity не содежит имя пользователя
            if (string.IsNullOrEmpty(model.UserName)) { model.UserName = "erroruser"; }
            _context.SaveDBBox(model);

#if RELEASE
            {
                BoxDBDataTest boxDB = _context.BoxesTestSaved.FirstOrDefault(b => b.Id == model.Id);
                if (boxDB is null)
                {
                    boxDB = new BoxDBDataTest()
                    {
                        Id = model.Id,
                        FullName = model.FullName,
                        BitrixLink = model.BitrixLink,
                        TypeBox = model.TypeBoxe,
                        UserId = _context.Users.First(u => u.UserName == User.Identity.Name).Id,
                        DateCreated = DateTime.Now
                    };
                    _context.BoxesTestSaved.Add(boxDB);
                }
                else
                {
                    boxDB.FullName = model.FullName;
                    boxDB.DateCreated = DateTime.Now;
                }
                _context.SaveChanges();
            }
#endif
            Id = model.Id;
            if (model == null) return RedirectToAction("FunError", "Home");
            return RedirectToAction($"Preview", routeValues: new { Id });
        }
        //создает клона модели, просто стирает Id и вписывает нового создателя
        //НИКТО НЕ ПОЛЬЗУЕТСЯ
        [HttpGet("Clone/{Id}")]
        public IActionResult Clone(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model != null)
            {
                model.UserName = User?.Identity?.Name;
                if (string.IsNullOrEmpty(model.UserName)) { model.UserName = "erroruser"; }
                model.Id = $"{model.GetType().Name}";
                return View("~/Views/Boxes/Index.cshtml", model);
            }
            return RedirectToAction("FunError", "Home");
        }
        //выводит станицу с параметрами модели и себестоимостью
        [HttpGet("Preview/{Id}")]
        public IActionResult Preview(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");
            return View(model);
        }
        //страница Preview выводит только параметры без себестоимости
        //себестоимоть выводится через ajax запрос к методу ниже
        //если ajax-у вернулся error то пытается вызвать этот метод, который выводит всё сразу
        [HttpGet("PreviewAJAXERROR/{Id}")]
        public IActionResult PreviewAJAXERROR(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");
            return View(model);
        }
        //метод для обработки ajax запроса со страницы Preview
        [HttpGet("CostViewJquery")]
        public IActionResult CostViewJquery(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);

            if (model == null) return RedirectToAction("FunError", "Home");
            model.Create();

            return View(model);
        }
        
        //сохранить в личный список заказов
        [HttpGet("Save/{Id}")]
        public IActionResult Save(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");
            model.Id = $"{System.Guid.NewGuid()}";
            _context.SaveDBBox(model);
            BoxDBData boxDB = new BoxDBData()
            {
                Id = model.Id,
                FullName = model.FullName,
                BitrixLink = model.BitrixLink,
                TypeBox = model.TypeBoxe,
                UserId = _context.Users.First(u => u.UserName == User.Identity.Name).Id,
                DateCreated = DateTime.Now
            };
            _context.BoxesSaved.Add(boxDB);
            _context.SaveChanges();
            return RedirectToAction($"Index", "JSONBox");
        }
        //скачать чертежи, раскрой, упаковку
        [HttpGet("Download/{Id}")]
        public FileResult Download(string Id)
        {
            string Path = $"{_webHostEnvironment.WebRootPath}\\FileTemp\\{System.Guid.NewGuid()}";
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return null;
            if (Directory.CreateDirectory(Path) != null)
            {
                model.Create(Path);
                ZipFile.CreateFromDirectory(Path, $"{Path}.zip");
                Task.Run(() => DeleteCreationFiles(Path));
                System.IO.FileStream fs = new System.IO.FileStream($"{Path}.zip", System.IO.FileMode.Open);
                return File(fs, "application/octet-stream", $"{model.FullName}.zip");
            }
            return null;
            //удаляет созданую папку и архив через минутя 
            static void DeleteCreationFiles(string Path)
            {
                Thread.Sleep(TimeSpan.FromMinutes(1));
                Directory.Delete(Path, true);
                System.IO.File.Delete($"{Path}.zip");
            }
        }
        //скачать крой для дизайнеров
        [HttpGet("DownloadDisign/{Id}")]
        public FileResult DownloadDisign(string Id)
        {
            string Path = $"{_webHostEnvironment.WebRootPath}\\FileTemp\\{System.Guid.NewGuid()}.pdf";
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return null;
            string PathConst = $"{_webHostEnvironment.WebRootPath}\\BoxesDisigns\\{model.GetType().Name}.pdf";

            model.CreateDisignPDF(PathConst, Path);
            Task.Run(() => DeleteCreationFile(Path));
            System.IO.FileStream fs = new System.IO.FileStream($"{Path}", System.IO.FileMode.Open);
            return File(fs, "application/pdf", $"{model.FullName}.pdf");

            static void DeleteCreationFile(string Path)
            {
                Thread.Sleep(TimeSpan.FromMinutes(1));
                System.IO.File.Delete($"{Path}");
            }

        }


        //создать сделку, запрос для получения ссылки на битрикс
        [HttpGet("DownloadOrder/{Id}")]
        public IActionResult DownloadOrder(string Id)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return RedirectToAction("FunError", "Home");

            ViewBag.BoxId = Id;
            ViewBag.BoxName = model.FullName;
            ViewBag.BitrixLink = model.BitrixLink;
            return View("~/Views/Boxes/DownloadOrder.cshtml");
        }
        [HttpPost("DownloadOrder/{Id}")]
        public IActionResult DownloadOrder(string Id, string BitrixLink)
        {
            BaseBox model = _context.GetDBBox(Id);
            if (model == null) return null;
            if (string.IsNullOrEmpty(BitrixLink) || !Uri.IsWellFormedUriString(BitrixLink, UriKind.Absolute) || !(new[] { "bitrix24", "likepackage" }.Any(s => BitrixLink.Contains(s) is true)))
            {
                ModelState.AddModelError("", "ссылка на bitrix24 обязательна");
                ViewBag.BoxId = Id;
                ViewBag.BoxName = model.FullName;
                return View("~/Views/Boxes/DownloadOrder.cshtml");
            }
            model.BitrixLink = BitrixLink;
            model.Create();
            _context.SaveDBBox(model);

InputValues/Views/Boxes/BoxToPngView.cshtml
@{
    Layout = null;
    CooverBoxWebApplication.Models.Boxes.BaseBox ModelBox = ViewBag.ModelBox;
    int BoxFileId = ViewBag.BoxFileId;
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        @@import url('https://likepackage.dp.ua/lib/bootswatch/solar/bootstrap.css');
    </style>
</head>
<fieldset>
    <legend class="text-white">@($"{ModelBox?.Name} {ModelBox?.X}x{ModelBox?.Y}x{ModelBox?.H} - {ModelBox?.N}  #{BoxFileId}")</legend>
    <div class="jumbotron">
        <div class="lead row m-1">
            <p class="col-md-4">@($"Тип")</p>
            <p class="col-md-8 text-white">@($"{ModelBox?.TypeBoxe}")</p>
        </div>
        @await Component.InvokeAsync("InputValueDisplay", new { model = ModelBox })
    </div>
</fieldset>

InputValues/Views/Boxes/DownloadOrder.cshtml
@{
    ViewData["Title"] = "Создание сделки";

}

<form asp-action="DownloadOrder" asp-route-Type="@(ViewBag.BoxType)" asp-controller="Boxes" method="post" asp-anti-forgery="true">
    <fieldset>
        <legend>@($"Создание сделки {ViewBag.BoxName}")</legend>
    </fieldset>
    <div class="validation text-warning" asp-validation-summary="ModelOnly"></div>
    <div class="jumbotron col-auto">
        <div class="form-group col-auto row">
            <label class="control-label col-md-3 col-xs-12" for="BitrixLink">Ссылка на Bitrix</label>
            <div class="col-md-9 col-xs-12">
                <input class="form-control" type="text" id="BitrixLink" name="BitrixLink" data-val="true" data-val-required="Поле является обязательным." value="@(ViewBag.BitrixLink)">
            </div>
            <span class="col-md-12 col-xs-12 field-validation-valid text-warning" data-valmsg-for="BitrixLink" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="row col-12">
        <a asp-action="Preview" asp-route-Type="@(ViewBag.BoxType)" asp-controller="Boxes" class="btn btn-secondary col-md-4 col-12 m-2">Назад</a>
        <input class="btn btn-info col-md-4 col-12 m-2" type="submit" value="Создать сделку"  onclick="return confirm('Будет создана сделка. Вы уверены?')"/>
    </div>


</form>

@section scripts{
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

InputValues/Views/Boxes/Index.cshtml
@model CooverBoxWebApplication.Models.Boxes.BaseBox
@{
    ViewData["Title"] = (string.IsNullOrEmpty(Model.Name))? Model.TypeBoxe:Model.FullName;
}

<form asp-action="Index" asp-route-Id="@(Model.Id)" asp-controller="Boxes" method="post" asp-anti-forgery="true">
    <fieldset>
        <legend class="text-white">@($"{((string.IsNullOrEmpty(Model.Name)) ? Model.TypeBoxe : $"{Model.FullName} ({Model.TypeBoxe})")}")</legend>
    </fieldset>
    <div class="validation text-warning" asp-validation-summary="ModelOnly"></div>
    @await Component.InvokeAsync("InputValue", new { model = Model })
    <input class="btn btn-secondary" type="submit" value="Далее" />

</form>
@section stylesheet{
    <link href="~/lib/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/lib/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

InputValues/Views/Boxes/Preview.cshtml
@model CooverBoxWebApplication.Models.Boxes.BaseBox

@{
    ViewData["Title"] = $"{Model?.FullName}";
}

    <fieldset>
        <legend class="text-white">@($"{Model.FullName} ({Model.TypeBoxe})")</legend>

        <div id="costviewtop" class="text-center"><img src="~/Static/tenor.gif" /></div>
        <div id="funerror" class="text-center"></div>
            @await Component.InvokeAsync("InputValueDisplay", new { model = Model })
        <div id="costviewdown"></div>
        <div class="row mx-auto col-12">
            <div class="col-md-6  mx-auto">
                @if (User.Identity.Name == Model.UserName || User.IsInRole("master"))
                {
                    <a asp-action="Index" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-secondary col-12 m-2">Редактировать</a>
                }
                <a asp-action="Clone" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-secondary col-12 m-2">Копировать</a>
            </div>
            <div class="col-md-6  mx-auto">
                <a asp-action="Save" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-info col-12 m-2">Сохранить</a>
                <a asp-action="DownloadDisign" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-info col-12 m-2">Скачать дизайн</a>
            </div>
            <div class="row col-12  mx-auto">
                <a asp-action="DownloadOrder" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn mx-md-auto btn-success col-12 m-2">Создать сделку</a>
            </div>
            @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
            {
                <div class="row col-12  mx-auto">
                    <a asp-action="Download" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-success col-12 m-2">Скачать</a>

                </div>
            }
        </div>
    </fieldset>
@section scripts{
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "GET",
                url: "@Url.Action("CostViewJquery", "Boxes", new { Id = Model.Id })",
                success: function (response) {
                    $("#costviewtop").replaceWith($(response).filter(".costviewtop"));
                    $("#costviewdown").replaceWith($(response).filter(".costviewdown"));
                    $("#funerror").replaceWith($(response).find(".funerror"));
                    $("fieldset").on("click", "#paperlistcount", function () {
                        var item = $("#paperlistcountview");

                        if (item.attr("display") == "true") {
                            item.addClass("d-none")
                            item.attr("display", false);
                        } else {
                            item.removeClass("d-none")
                            item.attr("display", true);
                        }
                    });
                    $("fieldset").on("click", "#tabeldisplaybtn", function () {
                        var item = $("#tablecostview");

                        if (item.attr("display") == "true") {
                            item.addClass("d-none")
                            item.attr("display", false);
                        } else {
                            item.removeClass("d-none")
                            item.attr("display", true);
                        }
                    });
                },
                error: function () {
                    var url = "@Url.Action("PreviewAJAXERROR", "Boxes", new { Id = Model.Id })";
                    $(location).attr('href', url);
                }
            });
        });
    </script>
}

InputValues/Views/Boxes/PreviewAJAXERROR.cshtml
@model CooverBoxWebApplication.Models.Boxes.BaseBox

@{
    ViewData["Title"] = $"{Model?.FullName}";
}

<fieldset>
    <legend class="text-white">@($"{Model.FullName} ({Model.TypeBoxe})")</legend>
    @{Model.Create(); }
    @await Html.PartialAsync("~/Views/Boxes/CostViewJquery.cshtml", Model)
    <div class="jumbotron">
        @await Component.InvokeAsync("InputValueDisplay", new { model = Model })
    </div>
    <div id="costviewdown"></div>
    <div class="row mx-auto col-12">
        <div class="col-md-6  mx-auto">
            @if (User.Identity.Name == Model.UserName || User.IsInRole("master"))
            {
                <a asp-action="Index" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-secondary col-12 m-2">Редактировать</a>
            }
            <a asp-action="Clone" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-secondary col-12 m-2">Копировать</a>
        </div>
        <div class="col-md-6  mx-auto">
            <a asp-action="Save" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-info col-12 m-2">Сохранить</a>
            <a asp-action="DownloadDisign" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-info col-12 m-2">Скачать дизайн</a>
        </div>
        <div class="row col-12  mx-auto">
            <a asp-action="DownloadOrder" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn mx-md-auto btn-success col-12 m-2">Создать сделку</a>
        </div>
        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
        {
            <div class="row col-12  mx-auto">
                <a asp-action="Download" asp-route-Id="@(Model.Id)" asp-controller="Boxes" class="btn btn-success col-12 m-2">Скачать</a>

            </div>
        }
    </div>
</fieldset>
@section scripts{
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(document).ready(function () {
            $("#costviewdown").replaceWith($(".costviewdown"));
        });
        $("#paperlistcount").click(function () {
            var item = $("#paperlistcountview");

            if (item.attr("display") == "true") {
                item.addClass("d-none")
                item.attr("display", false);
            } else {
                item.removeClass("d-none")
                item.attr("display", true);
            }
        });
        $("#tabeldisplaybtn").click(function () {
            var item = $("#tablecostview");

            if (item.attr("display") == "true") {
                item.addClass("d-none")
                item.attr("display", false);
            } else {
                item.removeClass("d-none")
                item.attr("display", true);
            }
        });
    </script>
}